FROM docker.elastic.co/logstash/logstash:8.11.2

COPY ./logstash.conf /usr/share/logstash/pipeline/logstash.conf
COPY ./logstash.yml /usr/share/logstash/config/logstash.yml


ENV LS_JAVA_OPTS="-Xmx512m -Xms256m"

RUN logstash-plugin install logstash-input-kinesis

EXPOSE 5000
EXPOSE 5044
EXPOSE 9600
