version: '3.7'

services:

  wordpress:
    image: wordpress:nicblog-6.1.1
    volumes:
      - ./blog_wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: host:port
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pwssssss
      WORDPRESS_DB_NAME: dbname
    deploy:
      labels:
        feature.description: 'Wordpress Blog UI'
      placement:
        constraints: [node.role == manager]
