version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elasticpassword
      discovery.type: single-node
      network.publish_host: _eth0_
    volumes:
      - ./data/elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.2
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./data/logstashdata:/usr/share/logstash/data
      - ./data/sincedb:/usr/share/logstash/.sincedb
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.2
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=another_user
      - ELASTICSEARCH_PASSWORD=changeme1
      - XPACK_SECURITY_ENABLED=true

    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
  

configs:
  elastic_config:
    file: ./configs/elasticsearch.yml
  logstash_config:
    file: ./workingconfigs/logstashconfig.yml
  logstash_pipeline:
    file: ./workingconfigs/logstashpipeline.conf
  kibana_config:
    file: ./configs/kibana.yml

networks:
  elk:
    driver: overlay
