version: '3.8'

services:
  fleet:
    image: docker.elastic.co/beats/elastic-agent:8.11.2
    ports:
      - 8220:8220
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://192.168.1.102:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3MDQ3OTc5NDgxNTc6Nmx6X05DSWtUTWU1T3gyX2xKNnZEUQ
      - FLEET_URL=http://192.168.1.102:8220
      - FLEET_SERVER_ELASTICSEARCH_USERNAME=elastic
      - FLEET_SERVER_ELASTICSEARCH_PASSWORD=elasticpassword
      - ELASTICSEARCH_HOST=http://192.168.1.102:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elasticpassword
      - KIBANA_FLEET_SETUP=1
      - KIBANA_HOST=http://192.168.1.102:5601
      - KIBANA_USERNAME=another_user
      - KIBANA_PASSWORD=changeme1
    networks:
      - elk

networks:
  elk:
    driver: overlay

configs:
  elastic-agent:
    file: ./configs/elastic-agent.yml
