apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: namespacename
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location /portainer/ {
            proxy_pass http://127.0.0.1:9000/;
            # Strip the /portainer prefix from the request
            rewrite ^/portainer(.*)$ $1 break;
        
            # Handle websockets
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #proxy_set_header X-Forwarded-Proto $scheme;
            #proxy_redirect     off;
        }

    }
