secret_path: "secret/data/occs/keycloak"

keycloak:
    url: "keycloak.domain.com"
    http:
        port: 8080
    https:
        port: 8443
        key: /opt/keycloak/conf/server.key.pem
        crt: /opt/keycloak/conf/server.crt.pem
    loglevel: "DEBUG"
    database:
        name: postgres
    realm:
        name: "occs"


    clients:
        selenium:
            url: "https://selenium-grid.domain.com"
            clientid: "selenium"
            username: "selenium"
        sonarqube:
            url: "https://sonarqube.domain.com"
            clientid: "sonarqube"
            username: "sonarqube"
        vault:
            url: "https://vault.domain.com"
            clientid: "vault"
            username: "vault"
        traefik:
            url: "https://traefik.domain.com"
            clientid: "traefik"
            username: "traefik"
